#!/usr/bin/python
import markovchain
from optparse import OptionParser

usage = "markov [options] corpus1 corpus2 ..."

parser = OptionParser()
parser.add_option("-l", "--lookback", dest="lookback",
                  help="number of characters to look back in the chain", metavar="LOOKBACK", default=2)
parser.add_option("-d", "--dictionary", dest="dictionary",
                  help="dictionary file to use", metavar="DICTIONARY", default='small_dict.txt')


(options, args) = parser.parse_args()
if (len(args) == 0):
  print usage
  exit()
m = markovchain.MarkovChain(args, options.dictionary, int(options.lookback))
print m
